DEFAULT_EXCEPTIONS = [ "chrome.exe", "firefox.exe", "msedge.exe",]
MUTE_GROUPS = [ [ "steam.exe", "steamwebhelper.exe",],]

[WINDOW]
min_width = 300
min_height = 500
width = 400
height = 600
background_color = "#2b2b2b"
foreground_color = "white"
button_color = "#3c3f41"
active_color = "#4b6eaf"
