DEFAULT_EXCEPTIONS = [ "chrome.exe", "firefox.exe", "msedge.exe",]
MUTE_GROUPS = [ "steam.exe", "steamwebhelper.exe",]
PID_MATCH_APPS = []
HIDE_TITLEBAR_APPS = [ "HeavenBurnsRed.exe",]

[APP_VOLUMES]
"chrome.exe" = 41
"firefox.exe" = 100
"msedge.exe" = 100
"HeavenBurnsRed.exe" = 22
"s.exe" = 100

[WINDOW]
min_width = 300
min_height = 500
width = 400
height = 600
background_color = "#2b2b2b"
foreground_color = "white"
button_color = "#3c3f41"
active_color = "#4b6eaf"
