DEFAULT_EXCEPTIONS = [ "chrome.exe", "firefox.exe", "msedge.exe",]
MUTE_GROUPS = [ "steam.exe", "steamwebhelper.exe",]
PID_MATCH_APPS = []
HIDE_TITLEBAR_APPS = [ "StarRail.exe", "GF2_Exilium.exe", "AtelierResleriana.exe", "Ad Fundum.exe", "P3R.exe", "VIRTUA_UNLIMITED_PROJECT.exe", "revolution.exe", "Awaken.exe", "HeavenBurnsRed.exe", "nikke.exe",]
MAXIMIZE_APPS = [ "s.exe",]
ALWAYS_ON_TOP_APPS = []

[BORDER_STYLES]
"HeavenBurnsRed.exe" = "no_change"
"Awaken.exe" = "none"

[WINDOW_PLACEMENTS]
"HeavenBurnsRed.exe" = "top_left"
"StarRail.exe" = "top_left"
"GF2_Exilium.exe" = "top_right"
"AtelierResleriana.exe" = "top"
"Ad Fundum.exe" = "top"
"P3R.exe" = "top"
"VIRTUA_UNLIMITED_PROJECT.exe" = "top"
"revolution.exe" = "top"
"Awaken.exe" = "top"
"nikke.exe" = "top_left"

[APP_VOLUMES]
"chrome.exe" = 41
"firefox.exe" = 100
"msedge.exe" = 100
"HeavenBurnsRed.exe" = 6
"s.exe" = 100
"StarRail.exe" = 18
"GF2_Exilium.exe" = 7

[WINDOW]
min_width = 300
min_height = 500
width = 400
height = 600
background_color = "#2b2b2b"
foreground_color = "white"
button_color = "#3c3f41"
active_color = "#4b6eaf"

[OPTIONS]
window_check_interval = 5000
volume_check_interval = 100
list_update_interval = 100
debug_mode = false

[STARTUP_DELAYS]
"P3R.exe" = 10
"VIRTUA_UNLIMITED_PROJECT.exe" = 10
"HeavenBurnsRed.exe" = 7
"steam.exe" = 0

[CUSTOM_RESOLUTION_APPS."StarRail.exe"]
width = 1920
height = 1080

[CUSTOM_RESOLUTION_APPS."GF2_Exilium.exe"]
width = 1280
height = 720

[CUSTOM_RESOLUTION_APPS."AtelierResleriana.exe"]
width = "fit_21_9"
height = "fit_21_9"

[CUSTOM_RESOLUTION_APPS."Ad Fundum.exe"]
width = "fit_24_9"
height = "fit_24_9"

[CUSTOM_RESOLUTION_APPS."P3R.exe"]
width = "fit_21_9"
height = "fit_21_9"

[CUSTOM_RESOLUTION_APPS."VIRTUA_UNLIMITED_PROJECT.exe"]
width = "fit_21_9"
height = "fit_21_9"

[CUSTOM_RESOLUTION_APPS."revolution.exe"]
width = "fit_21_9"
height = "fit_21_9"

[CUSTOM_RESOLUTION_APPS."Awaken.exe"]
width = "fit_21_9"
height = "fit_21_9"

[CUSTOM_RESOLUTION_APPS."HeavenBurnsRed.exe"]
width = 3840
height = 2160

[CUSTOM_RESOLUTION_APPS."nikke.exe"]
width = "fit_3_4"
height = "fit_3_4"
