CURRENT_EXCEPTIONS = [ "firefox.exe", "msedge.exe",]

[SETTINGS]
mute_last_app = 1
force_mute_fg = 0
force_mute_bg = 0
mute_foreground_when_background = 0
lock = 0

[WINDOW_STATE]
geometry = "527x577+130+32"
maximized = false
