CURRENT_EXCEPTIONS = [ "firefox.exe", "msedge.exe", "chrome.exe", "python3.9.exe", "NVIDIA Overlay.exe", "vlc.exe", "Microsoft.Media.Player.exe", "nikke.exe", "GF2_Exilium.exe", "HeavenBurnsRed.exe",]

[SETTINGS]
mute_last_app = 1
force_mute_fg = 0
force_mute_bg = 0
mute_foreground_when_background = 0
lock = 0

[WINDOW_STATE]
geometry = "1916x678+1500+1235"
maximized = false

[VOLUME_WINDOW_STATE]
geometry = "2519x469+9+1527"
maximized = false
